spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            clientId: qWhczN_Zlnam_CbdEpZ5
            client-secret: ENUoaAIZku
          kakao:
            clientId: d879cdc8ed17378b7a388cdf7c401b64
          google:
            clientId: 358874638326-hrnecluhlrjcgl2pgi33ba677oi7mncj.apps.googleusercontent.com
            client-secret: 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
          facebook:
            clientId: 221329827203218
            client-secret: feaf575f5996f80ca3d54a6c0e85dfbe
          instagram:
            clientId: 3478905755762434
            client-secret: a3a2a6785e750a2ce9500c2ac031e2ea
custom:
  security:
    oauth2:
      client:
        registration:
          naver:
            devUserOauthId: 9xIgV-SJgWqRYtj3IX5zCOzvdQdTY2okeb9iXO2Zip4
          kakao:
            devUserOauthId: 2737088692
          google:
            devUserOauthId: 103240209825008011930
          facebook:
            devUserOauthId: 6275550032523900
